name: Defensor
version: 1.0.0
main: com.floodeer.plugins.towerdefense.Defensor
api-version: 1.19
depend: [ Citizens ]
softdepend: [ HolographicDisplays ]
authors: [ Floodeer ]
commands:
  defensor:
  td: